### ISSUE TITLE
2024-07-02 22:07:57 /opt/conda/bin/python3: No module named webui

### ISSUE THREAD

**Issue by haisheng666** [Pythonpa/UniAnimate-GradioUI#1]
![image](https://github.com/Pythonpa/UniAnimate-GradioUI/assets/42937758/181ea826-c66e-4dfb-abe1-e3ed35fdebeb)
What the hell? Please take a look

**Comment by Pythonpa** [comment]
What's your command of docker run?Did you use my suggested command?

**Comment by zhenyuanzhou** [comment]
Same here

**Comment by zhenyuanzhou** [comment]
python webui.py can run but with error 
发生错误：Command '['python', 'run_align_pose.py', '--ref_name', 'data/images/musk.jpg', '--source_video_paths', 'data/videos/dance.mp4', '--saved_pose_dir', 'data/saved_pose/dance']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "D:\PythonProject\UniAnimate-GradioUI\webui.py", line 49, in process_video
    subprocess.run([
  File "D:\PythonProject\UniAnimate-GradioUI\venv\lib\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', 'run_align_pose.py', '--ref_name', 'data/images/musk.jpg', '--source_video_paths', 'data/videos/dance.mp4', '--saved_pose_dir', 'data/saved_pose/dance']' returned non-zero exit status 1.

**Comment by zhenyuanzhou** [comment]
I find the issue
The code to run docker is wrong, try this one, the path should be D:\PythonProject\UniAnimate-GradioUI, but the code provided is is D:\PythonProject\UniAnimate

Try this one
docker run --gpus all -p 7860:7860 --name UniAnimate-webui -v D:\PythonProject\UniAnimate-GradioUI:/workspace/UniAnimate -w /workspace/UniAnimate -d aimaster104/unianimate:webui python3 -m webui

**Comment by haisheng666** [comment]
> 你对docker run的命令是什么？你用了我建议的命令吗？
yes


> What's your command of docker run?Did you use my suggested command?

Please verify the availability before uploading, otherwise your project will not get one star.

**Comment by Pythonpa** [comment]
> I find the issue 我发现问题所在 The code to run docker is wrong, try this one, the path should be D:\PythonProject\UniAnimate-GradioUI, but the code provided is is D:\PythonProject\UniAnimate运行 docker 的代码是错误的，试试这个，路径应该是 D：\PythonProject\UniAnimate-GradioUI，但提供的代码是 D：\PythonProject\UniAnimate
> 
> Try this one 试试这个 docker run --gpus all -p 7860:7860 --name UniAnimate-webui -v D:\PythonProject\UniAnimate-GradioUI:/workspace/UniAnimate -w /workspace/UniAnimate -d aimaster104/unianimate:webui python3 -m webuidocker run --gpus all -p 7860：7860 --name UniAnimate-webui -v D：\PythonProject\UniAnimate-GradioUI：/workspace/UniAnimate -w /workspace/UniAnimate -d aimaster104/unianimate：webui python3 -m webui

got it,will fix it
